export const publicImages = {
  buzLogo: 'assets/logo/BuzLogo.svg',
  heroSectionImage: 'assets/images/hero-section.svg',
  '24HrsImage': 'assets/logo/24hrs.svg',
  arrow: 'assets/logo/arrow.svg',
  location: 'assets/logo/location.svg',
  rupees: 'assets/logo/rupees.svg',
  safety: 'assets/logo/safety.svg',
  heroSectionBrand: 'assets/images/hero-section-brand.svg',
  autoBooking: 'assets/images/autoBooking.svg',
  bikeBooking: 'assets/images/bikeBooking.svg',
  cabBooking: 'assets/images/cabBooking.svg',
  bike: 'assets/logo/bike.svg',
  clock: 'assets/logo/clock.svg',
  buzzcabMobileImg: 'assets/images/buzzcabMobileImg.svg',
  avatar: 'assets/logo/avatar.svg',
  referAndEarn: 'assets/images/referAndEarn.svg',
  comingSoon: 'assets/images/comingSoon.svg',
  facebook: 'assets/logo/facebook.svg',
  instagram: 'assets/logo/instagram.svg',
  linkedin: 'assets/logo/linkedin.svg',
  youtube: 'assets/logo/youtube.png',
  aboutImg1: 'assets/images/aboutImg1.png',
  aboutImg2: 'assets/images/aboutImg2.png',
  aboutImg3: 'assets/images/aboutImg3.png',
  aboutImg4: 'assets/images/aboutImg4.png',
  aboutImg5: 'assets/images/aboutImg5.png',
}
